# Generated by Django 4.2 on 2023-04-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('firm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.firm')),
            ],
        ),
    ]
