# Generated by Django 4.2 on 2023-04-20 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='inbox_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
