# Generated by Django 4.2 on 2023-04-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_firm_inbox_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
