# Generated by Django 4.2 on 2023-04-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='firm_id',
            new_name='firm',
        ),
    ]
