# Generated by Django 4.2 on 2023-04-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_rename_firm_id_lead_firm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='email',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='first_name',
            new_name='from_first',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='last_name',
            new_name='from_last',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='message',
            new_name='from_message',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='phone',
            new_name='from_phone',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='source',
            new_name='from_source',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='url',
            new_name='referring_url',
        ),
    ]
