# Generated by Django 4.2 on 2023-05-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_lead_firm_alter_lead_from_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='from_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='from_first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='from_last',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='from_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='from_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='from_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='referring_url',
            new_name='url',
        ),
    ]
